### ISSUE TITLE
Intermittent upload failures in Safari (desktop and iOS)

### ISSUE THREAD

**Issue by mzruya** [m-lab/ndt7-js#19]
Hey. Thank you for the work on ndt7-js.
I've been using the library for a hobby "speed test" project and integrating it has been rather smooth.
I have noticed an issue in the upload test. While running it in Safari. The web socket connection fails. This manifests as the following error message in the web console:

> WebSocket network error: The operation couldn’t be completed. Broken pipe

When it happens, `sock.onerror` is triggered, but the event doesn't seem to contain any useful information:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/653256/110224298-44465e80-7ea8-11eb-950f-070fc08ca70d.png">

This tends to happen at the end of the upload test (after 10 seconds). The test hangs (as in no new measurements come in), and then the error shows up.

Reducing the [buffer size](https://github.com/m-lab/ndt7-js/blob/main/src/ndt7-upload-worker.js#L93) to  `const desiredBuffer = data.length;` seems to mitigate it and increasing the multiple worsens the issue.

This happens in both desktop and iOS Safari. both seems to reproduce much more frequently on iOS.
It hasn't been an issue for both Firefox and Chrome.

This seems to point at stricter memory limits around web sockets in Safari. Although I couldn't find any documentation to corroborate it.

**Comment by stephen-soltesz** [comment]
@robertodauria a summary of your recent investigation may be helpful here.

**Comment by robertodauria** [comment]
I think this is the other issue related to the upload test, which should have been fixed ~a week ago. It's caused by the browser waiting to send all the data in its buffer before closing the WebSocket connection. After 15 seconds (5 seconds after the upload test ended) the server forcefully terminates the connection, causing that `Broken pipe`. Since at that point the measurement is complete and we are not interested in sending the remaining data in the buffer, now the client just terminates the upload worker after 10s -- as per [this](https://github.com/m-lab/ndt7-js/pull/18/files) PR.

@mzruya could you please make sure you are using the latest version on the `main` branch (v0.0.4 on npm)?

I'll also mention that Safari/WebKit is known to have a different issue with the upload test: when sending data, the `sock.bufferedAmount` property is not updated immediately and the loop filling the buffer (https://github.com/m-lab/ndt7-js/blob/main/src/ndt7-upload-worker.js#L102) easily overfills it and causes the next `send()` to fail, terminating the upload in advance with a "Failed to send WebSocket frame" error on very fast connections.

The fact `bufferedAmount` is not updated timely seems an issue within WebKit I don't think we can work around. Without knowing how much data is in the buffer we can't know whether to queue more data for sending or not. Reducing the frame size and/or the `desiredBuffer` appears to help but the upload may still fail on faster connections (I tested up to 1Gbps and still saw occasional failures) or impact measurement quality. For the time being, we are going to recommend not using Safari to run ndt7 measurements. Other browsers such as Firefox and Google Chrome all seem to work as intended.

**Comment by ahardewig** [comment]
Hey guys, just wanted to share some findings on this issue. For some background, we've been using ndt for speedtests for a little over a year. We forked the ndt7-js client to add some custom logic. We noticed that ndt7 seemed to fail on safari so, until now, our solution has been to run the ndt5 client for safari and ndt7 for all non-safari. Recently we had some extra dev time so we tried to figure out why ndt5 seemed to work fine on safari and ndt7 seemed to fail. I'll echo some of the above but here's what we were able to discover:

1) Safari websockets don't seem to accurately report `sock.bufferedAmount`. It appears that it lags behind the true value because we can see it report size 0 for a while after we've been sending data. (We are unsure if its a "slow start" issue where after x amount of time, it accurately reports the value or if its an "eventual consistency" issue where the value is always stale and not necessarily the most up to date.)

2) Websockets terminate if the upload buffer overflows (this is expected behavior in all browsers afaik)

3) NDT7 has adaptive message sizes beginning at 8192 and ending at 16MB. NDT5 appears to send a constant 1MB payload during the upload test.

These 3 behaviors seem to create the perfect storm for Safari. The adaptive message size quickly increases the payload size because `sock.bufferedAmount` continues to erroneously report size = 0. Because the payload quickly reaches 16MB, there is a good chance that slower clients fail to evict bytes out of the buffer before it overflows, causing the upload test to terminate.

We are still doing additional validation to confirm our fix, but its shown some success so far. We don't want to create lots of extra conditions by turning adaptive message sizes on or off, so instead we've adapted the upload worker to take in a config with an override for maxMessageSize. This essentially makes the change in upload worker limited to a single line
`const maxMessageSize = maxMessageSizeOverride ?? 16777216;`.

The client consuming the NDT7-js package should determine whether it is being run on safari. If it is, it should pass in a maxMessageSizeOverride that its comfortable with (we are experimenting with 1MB), otherwise it can pass in no config and rely on 16MB maxMessageSize. 

We are still trying to perform some additional tests on slower connections to determine if the 1MB max size is sufficient to prevent early terminations but we had lots of success with NDT5 (which sends constant 1MB payloads) and hope this will allow the ndt7 client to run on all browsers.


Additionally, because `sock.bufferedAmount` is used in the calculation of numBytes, it might be more accurate or safer to use the response from the server. It looks like the `TCPInfo` object has `BytesReceived` and `ElapsedTime` to perform the upload speed calculation. Any thoughts on this approach? Is there anything that I'm missing or overlooking that could negatively impact accuracy or results quality? We'd be happy to take a look at contributing this upstream if this approach is acceptable

**Comment by RA80533** [comment]
While I haven't done enough research into the internals of this issue to warrant anything more than suspicion for some of the behaviors discussed in this thread, I'd like to offer a few thoughts:

1)

> I think this is the other issue related to the upload test, which should have been fixed ~a week ago. It's caused by the browser waiting to send all the data in its buffer before closing the WebSocket connection. After 15 seconds (5 seconds after the upload test ended) the server forcefully terminates the connection, causing that Broken pipe. Since at that point the measurement is complete and we are not interested in sending the remaining data in the buffer, now the client just terminates the upload worker after 10s -- as per [this](#18) PR.

https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket-close

> The `close()` method does not discard previously sent messages before starting the WebSocket closing handshake — even if, in practice, the user agent is still busy sending those messages, the handshake will only start after the messages are sent.

2)

https://github.com/m-lab/ndt7-js/blob/1150c12d1fb1b28a1cea6eff64c4b2c18cc8288a/src/ndt7-upload-worker.js#L102-L109

> ```

> // The buffering bound prevents us from wasting local memory, the time bound
 // prevents us from stalling the UI event loop, and the sizeIncrement bound
    // allows us to dynamically respond to fast connections.

**Comment by RA80533** [comment]
> ```The buffering bound prevents us from wasting local memory, the time bound
 // prevents us from stalling the UI event loop, and the sizeIncrement bound
    // allows us to dynamically respond to fast connections.

**Comment by robertodauria** [comment]
This bug (along with #44) has been fixed now. Please feel free to reopen if you see it happening again with the latest ndt7-js version (`@m-lab/ndt7:0.0.5`)
