### ISSUE TITLE
example does not always work

### ISSUE THREAD

**Issue by why36** [m-lab/ndt7-js#51]
When I try to run the example like "node ndt7-js/examples/node-client.js", sometimes it may works, but frequently I got such error:
 
/home/why/ndt7-js/examples/node-client.js:24
        const serverBw = data.LastServerMeasurement.BBRInfo.BW * 8 / 1000000;
                                                    ^

TypeError: Cannot read property 'BBRInfo' of undefined
    at Object.downloadComplete [as complete] (/home/why/ndt7-js/examples/node-client.js:24:53)
    at Worker.worker.resolve (/home/why/ndt7-js/src/ndt7.js:150:21)
    at Timeout._onTimeout (/home/why/ndt7-js/src/ndt7.js:163:31)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)

I am really confused because I did not change anything,why?

**Comment by KamWithK** [comment]
I also get this exact error. Oddly though it only occurs when I run on my browser (not when I try it within runkit).
When I log the data object all of its properties (for example `LastClientMeasurement` but not limited to it) are undefined :(.

Does anyone potentially know why it happens/how to solve it?

**Comment by laiyi-ohlsen** [comment]
@why36 thanks for reporting. @robertodauria do you have thoughts?

**Comment by KamWithK** [comment]
Works on RunKit, yet to try it out locally

**Comment by robertodauria** [comment]
Adding some more details about the issue and what was changed here:

- The `complete` callback was being called regardless of the `exitcode` coming from the download/upload workers
- In case no messages have been received at all from the server (so, `sock.onmessage` has never been called), there is no `LastServerMeasurement`
- When the Locate service (which returns a server geographically close to you) cannot be contacted before the test this would previously not terminate the test workers, which would then proceed to timeout after 10s, call `complete` incorrectly (due to the above) and generate the error you're reporting

It's still unclear why getting the server URLs from the Locate service might have failed in the first place. Just in case, you can manually verify that you can connect to Locate by opening https://locate.measurementlab.net/v2/nearest/ndt/ndt7 in your browser (or with `curl`) from the same machine you're using to run the ndt7-js client. The expected output is a JSON containing a list of 4 M-Lab machines and the corresponding URLs to start download/upload tests.

Another option is that Locate worked, but the test machine could not be contacted for some reason. The additional error logging should help us figure out if that's the case.
